# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(201, 383)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.priceInput = QtWidgets.QSpinBox(self.centralwidget)
        self.priceInput.setGeometry(QtCore.QRect(10, 230, 181, 22))
        self.priceInput.setObjectName("priceInput")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(120, 310, 71, 23))
        self.saveButton.setObjectName("saveButton")
        self.formInput = QtWidgets.QComboBox(self.centralwidget)
        self.formInput.setGeometry(QtCore.QRect(10, 130, 181, 21))
        self.formInput.setObjectName("formInput")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.nameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.nameInput.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.nameInput.setObjectName("nameInput")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 47, 13))
        self.label_5.setObjectName("label_5")
        self.tasteInput = QtWidgets.QLineEdit(self.centralwidget)
        self.tasteInput.setGeometry(QtCore.QRect(10, 180, 181, 20))
        self.tasteInput.setObjectName("tasteInput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label_2.setObjectName("label_2")
        self.volumeInput = QtWidgets.QSpinBox(self.centralwidget)
        self.volumeInput.setGeometry(QtCore.QRect(10, 280, 181, 22))
        self.volumeInput.setObjectName("volumeInput")
        self.roastinInput = QtWidgets.QComboBox(self.centralwidget)
        self.roastinInput.setGeometry(QtCore.QRect(10, 80, 181, 22))
        self.roastinInput.setObjectName("roastinInput")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 201, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
        self.label_3.setText(_translate("MainWindow", "Форма"))
        self.label_5.setText(_translate("MainWindow", "Цена"))
        self.label_2.setText(_translate("MainWindow", "Обжарка"))
        self.label_4.setText(_translate("MainWindow", "Вкус"))
        self.label_6.setText(_translate("MainWindow", "Объём"))
        self.label.setText(_translate("MainWindow", "Сорт"))
